### PR TITLE
Some more script cleanups

### PR DESCRIPTION
**Pull request by NiLuJe**
I'd somehow forgotten about the final block ;).

I'm still not getting it to actually connect to Calibre, but I now have more info:

When I mentioned that it hanged during the "Running Kobo-UNCaGED" step, I actually failed to notice that it's actually chugging along at 100% CPU, so I assume it's doing... something ;).

Then it finally prints "Connecting to Calibre", but doesn't actually connect, and it then fairly quickly returns -1

The second hang is then FBInk waiting for a processing pass that never happens, until it finally exits w/ ENODATA

### CODE REVIEW

**Comment by NiLuJe** [comment]
i.e., my final log entry is

`May  2 19:13:50 UNCaGED: Nothing more to do? (KU: 255; BS: 61)`

**Comment by shermp** [comment]
Good morning NiLuJe,

Hopefully I'll have a chance to get KU installed on my Kobo this morning and do some debugging. Now that the scripts are sorted out, that should make debugging things a lot easier.

**Comment by shermp** [comment]
I've merged the changes. We can change the above comment at a later date.

**Comment by NiLuJe** [comment]
Yeah, making that bypassable sounds good, and/or forgetting about it for now ;).

This was mainly because I *think* this has the greatest potential of screwing things up, and the only crash I ever got was during a run while plugged in ;).

But, yeah, definitely agree that it might not make much sense for now.

**Comment by shermp** [comment]
I definitely think it's a good idea to have, because you're right, being attached to the PC would be the biggest danger of this whole mess...

**Comment by shermp** [comment]
I deleted a book. And transferred a book :D 

I haven't really changed anything @NiLuJe , so if it doesn't work, make sure Calibre is listening, and the ports aren't being blocked.

Issues so far:
* FBInk printing is not behaving how I want it to. It SHOULD show up in a centred box, with the previous contents being cleared for each print. I've probably got some sums wrong in `kuPrintEink.go`
* Need to improve status messages to let users have a better idea of what KU is doing, especially when waiting for cover thumbnails to be generated, which leads in to the next issue...
* Cover/thumbnail generation is s l o w. Like really slow. I obviously need to find a faster library to do this. Probably needs to be based on a C/C++ lib with ARM optimizations.

**Pull request merged**
