### PR TITLE
Update koboutils dependency to v2.2.0

### PR DESCRIPTION
**Pull request by SmatMan**
Refer to #51

### CODE REVIEW

**Comment by shermp** [comment]
Hi, thanks to looking into this.

I think we as may as well update to the latest kobutils commit (`3392dec`). which also supports the new colour devices. Also feel free to update the Go version.

**Comment by shermp** [comment]
Oh, I see, the workflow sets Go 1.17

**Comment by SmatMan** [comment]
I didn't upgrade Go as it strangely didn't seem to build with 1.21
I'm updating to the latest koboutils commit at the moment.

**Comment by SmatMan** [comment]
Seemed to build fine with the dependency upgrade, I'm going to try to update Go now, but I don't have too much experience with go so I'm trying not to change too much haha

**Comment by SmatMan** [comment]
Go update didn't seem to work due to the error discussed in this issue: https://github.com/golang/go/issues/61888
Since I'm not too experienced with go, and since the build seems to work with go 1.17, I'm going to leave it as is. I'll test on my libra colour when I'm able!

**Pull request merged**
