### PR TITLE
Scripts cleanups

### PR DESCRIPTION
**Pull request by NiLuJe**
Better late that never ;).

I still haven't managed to actually get it to do anything, but at least now I can reliably get UNCaGED to actually run in the expected environment.

It just hangs for a while, before printing "Connecting to Calibre", then hangs for another while without actually connecting to Calibre, and then exits safely back to Nickel.

I'd suggest adding a bunch of logging *to syslog* around whatever it is UNCaGED is supposed to be doing to figure this out ;).
I did that in the scripts, and it's been incredibly helpful!

### CODE REVIEW

**Comment by NiLuJe** [comment]
On the upside, I never managed to break Nickel during all that time. I think at one time I crashed it and it rebooted, but that's it ;).

**Comment by NiLuJe** [comment]
I'd also probably ditch the custom device detection and just leech that from FBInk, as that kind of info is now exposed by `get_state` ;).

**Comment by shermp** [comment]
Thank you sooo much for looking at this, and improving the shell scripts. I hate shell scripting, so your assistance is very much appreciated!

**Comment by shermp** [comment]
And I feel a bit of a dummy for forgetting the obtain the IP address.

The mount options I had used were the options that I saw Nickel had mounted with, which is why they were what they were.

**Comment by NiLuJe** [comment]
Yeah, I was also initially checking `/proc/mounts`, until I remembered busybox could be finicky ;).

**Comment by shermp** [comment]
Oops, noticed a problem with the IP address release/obtain.

It breaks when Wifi is forced on from the debug settings. We probably need to do the IP address stuff in the enable/disable wifi functions instead.

**Comment by NiLuJe** [comment]
Oh, yeah, that makes perfect sense ;).

**Comment by shermp** [comment]
Note, that I made the change a while ago.

**Pull request merged**
